replicaCount: 2

image:
  repository: jamallasomasekhar/flask-app
  tag: latest
  pullPolicy: IfNotPresent

mongodb:
  image: mongo
  tag: latest

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    memory: "250Mi"
    cpu: "200m"
  limits:
    memory: "500Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
